name: Build & Publish Docker Images

env:
  BASE_TAG: 'jandi/php-apache'

on:
  push:
    branches:    
      - main

jobs:
  main:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build with PHP 7.4
        id: docker_build_7_4
        uses: docker/build-push-action@v2
        with:
          build-args: FROM_TAG=7.4-apache
          push: true
          tags: ${{ env.BASE_TAG }}:7.4, ${{ env.BASE_TAG }}:latest
          cache-from: type=registry,ref=${{ env.BASE_TAG }}:7.4
          cache-to: type=inline
      -
        name: Build with PHP 7.3
        id: docker_build_7_3
        uses: docker/build-push-action@v2
        with:
          build-args: FROM_TAG=7.3-apache
          push: true
          tags: ${{ env.BASE_TAG }}:7.3
          cache-from: type=registry,ref=${{ env.BASE_TAG }}:7.3
          cache-to: type=inline
      -
        name: Image digests
        run: |
          echo ${{ env.BASE_TAG }}:7.4 ${{ steps.docker_build_7_4.outputs.digest }}
          echo ${{ env.BASE_TAG }}:7.3 ${{ steps.docker_build_7_3.outputs.digest }}