name: Publish Docker Images
on:
  push:
    branches:    
      - master

jobs:
  main:
    name: Build & Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build PHP 7.4
        id: docker_build_7_4
        uses: docker/build-push-action@v2
        with:
          build-args: FROM_TAG=7.4-apache
          push: true
          tags: jandi/php-apache:7.4
      -
        name: Image digests
        run: echo 7.4 {{ steps.docker_build_7_4.outputs.digest }}